[package]
name = "game-math"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dev-dependencies]
simplebench-runtime = { path = "../../simplebench-runtime" }
simplebench-macros = { path = "../../simplebench-macros" }
rand = "0.8"
